name: Preview Deployment - web
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_WEB }}

# Add concurrency to cancel in-progress jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths: 
      - 'apps/web/**'
      - 'packages/**'

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Setup Bun
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Install Vercel CLI
      - name: Install Vercel CLI
        run: bun install --global vercel@latest

      # Install dependencies
      - name: Install Dependencies
        run: bun install

      # Generate Prisma Client
      - name: Generate Prisma Client
        run: bun run db:generate --filter=@coordinize/database

      # Pull Vercel Environment Information
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: apps/web

      # Build Project Artifacts
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: apps/web

      # Deploy Project Artifacts to Vercel
      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: apps/web