name: Preview Deployment - app
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_APP }}

# Add concurrency to cancel in-progress jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths: 
      - 'apps/app/**'
      - 'packages/**'
      - '*'
      - '!apps/web/**'

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Setup Bun
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Install dependencies
      - name: Install Dependencies
        run: bun install

      # Generate Prisma Client
      - name: Generate Prisma Client
        run: bun run db:generate --filter=@coordinize/database

      # Pull Vercel Environment Information
      - name: Pull Vercel Environment Information
        run: bunx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      # Build Project Artifacts
      - name: Build Project Artifacts
        run: bunx vercel build --token=${{ secrets.VERCEL_TOKEN }}

      # Deploy to Vercel
      - name: Deploy to Vercel
        run: bunx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}