name: Production Deployment - web
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_WEB }}

# Add concurrency to prevent multiple production deployments
concurrency:
  group: "production-web"
  cancel-in-progress: false

on:
  push:
    branches:
      - main
    paths: 
      - 'apps/web/**'
      - 'packages/**'

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Setup Bun
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Install Vercel CLI
      - name: Install Vercel CLI
        run: bun install --global vercel@latest

      # Install dependencies
      - name: Install Dependencies
        run: bun install

      # Generate Prisma Client (to ensure up-to-date client)
      - name: Generate Prisma Client
        run: bun run db:generate --filter=@coordinize/database

      # Run Prisma migrations (apply changes to production database)
      - name: Apply Prisma Migrations
        run: |
          cd packages/database
          npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Pull Vercel Environment Information
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: apps/web

      # Build Project Artifacts
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: apps/web

      # Deploy to Vercel Production
      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: apps/web